# Generated by Django 2.1.1 on 2018-12-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_salesman'),
        ('product', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstatistics',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='salesstatistics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesContract', verbose_name='销售合同'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='业务员'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesContract', verbose_name='销售合同'),
        ),
    ]
