# Generated by Django 2.1.1 on 2018-09-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20180921_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecontract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier', verbose_name='供应商'),
        ),
    ]
