# Generated by Django 2.1.1 on 2018-10-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20180926_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecontract',
            name='supplier',
        ),
    ]
