# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20181030_2128'),
        ('purchase', '0004_remove_purchasecontract_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='outbound_count',
            new_name='storage_count',
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier', verbose_name='供应商'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='bill_amount',
            field=models.FloatField(default=0, max_length=30, verbose_name='开票金额'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='bill_name',
            field=models.CharField(default='', max_length=30, verbose_name='开票名称'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='bill_quantity',
            field=models.IntegerField(default=0, verbose_name='开票数量'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='bill_unit',
            field=models.CharField(default='', max_length=30, verbose_name='开票单位'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='currency',
            field=models.CharField(default='', max_length=30, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='exrate',
            field=models.FloatField(default=1, verbose_name='汇率'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='not_bill_amount',
            field=models.FloatField(default=0, max_length=30, verbose_name='未开票金额'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='reviewer',
            field=models.CharField(default='', max_length=50, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='total_amount',
            field=models.FloatField(default=0, max_length=30, verbose_name='总金额'),
        ),
    ]
