# Generated by Django 2.0.5 on 2018-12-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='share_cost',
        ),
    ]
