# Generated by Django 2.0.5 on 2019-01-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsalesproduct',
            name='branch_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_sales_product', to='branch_sales.BranchSalesContract', verbose_name='分公司销售合同'),
        ),
    ]
