# Generated by Django 2.0.5 on 2019-01-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_sales', '0002_auto_20190109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsalescontract',
            name='status',
            field=models.IntegerField(choices=[(0, '报价阶段'), (1, '销售订单'), (2, '审核失败'), (3, '已出库(全部)'), (4, '已完成(收款完毕)'), (5, '欠款'), (6, '退货')], default=0, verbose_name='合同状态'),
        ),
    ]
