# Generated by Django 2.0.5 on 2019-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_sales', '0003_auto_20190109_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsalescontract',
            name='price_clause',
        ),
    ]
