# Generated by Django 2.1.1 on 2018-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50, verbose_name='币种')),
                ('type', models.CharField(max_length=20, verbose_name='兑换货币')),
                ('date', models.DateField(verbose_name='修改时间')),
                ('exchange_rate', models.FloatField(default=1, verbose_name='汇率')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
            },
        ),
    ]
