# Generated by Django 2.0.5 on 2018-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='continentsstate',
            name='a',
            field=models.BooleanField(default=False),
        ),
    ]
