# Generated by Django 2.0.5 on 2018-12-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_continentsstate_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continentsstate',
            name='a',
        ),
    ]
