# Generated by Django 2.0.5 on 2018-12-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='仓库名')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='总数量')),
                ('sr_count', models.IntegerField(default=0, verbose_name='在途数量')),
                ('por_count', models.IntegerField(default=0, verbose_name='需求数量')),
                ('unit_cost', models.FloatField(default=0, verbose_name='平均成本')),
                ('bad_count', models.IntegerField(default=0, verbose_name='不良品数量')),
                ('recent_date', models.DateField(verbose_name='最近入库时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库产品',
                'verbose_name_plural': '仓库产品',
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=20, verbose_name='申请人')),
                ('reviewer', models.CharField(max_length=20, verbose_name='审核人')),
                ('order_num', models.CharField(max_length=20, verbose_name='单号')),
                ('unit_price', models.FloatField(default=0, verbose_name='售价')),
                ('cost_unit_price', models.FloatField(default=0, verbose_name='成本')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('in_or_out', models.IntegerField(choices=[(0, '出库'), (1, '入库')], default=0, verbose_name='出/入库')),
                ('reason', models.CharField(default='normal', max_length=300, verbose_name='原因')),
                ('date', models.DateField(verbose_name='日期')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock', verbose_name='仓库')),
            ],
        ),
    ]
