# Generated by Django 2.1.1 on 2018-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercontacts',
            name='contacts',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank',
            field=models.CharField(default='', max_length=50, verbose_name='开户银行'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(default='', max_length=50, verbose_name='银行账户'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='duty_para',
            field=models.CharField(default='', max_length=50, verbose_name='税号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='eco_nature',
            field=models.CharField(default='', max_length=20, verbose_name='经济性质'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postalcode',
            field=models.CharField(default='', max_length=50, verbose_name='邮政编码'),
        ),
        migrations.AddField(
            model_name='suppliercontacts',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='suppliercontacts',
            name='fax',
            field=models.CharField(default='', max_length=50, verbose_name='传真'),
        ),
        migrations.AddField(
            model_name='suppliercontacts',
            name='master_contact',
            field=models.BooleanField(default=False, verbose_name='主联系人'),
        ),
        migrations.AddField(
            model_name='suppliercontacts',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='suppliercontacts',
            name='telephone',
            field=models.CharField(default='', max_length=50, verbose_name='手机号码'),
        ),
    ]
