# Generated by Django 2.1.1 on 2018-10-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchasecontract_supplier'),
        ('supplier', '0002_auto_20181019_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercontacts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierContacts',
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
