# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_suppliercontacts_supplierproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='客户名'),
        ),
    ]
