# Generated by Django 2.0.5 on 2019-01-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchclient',
            name='address',
            field=models.CharField(default='', help_text='客户地址', max_length=100, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='client_id',
            field=models.CharField(default='', help_text='客户代码', max_length=50, unique=True, verbose_name='客户代码'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='company_name',
            field=models.CharField(default='', help_text='客户公司名', max_length=100, verbose_name='客户公司名'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='credit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', help_text='客户信用', max_length=10, verbose_name='客户信用'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='info',
            field=models.CharField(default='', help_text='客户信息', max_length=100, verbose_name='客户信息'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='客户级别', max_length=10, verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='name',
            field=models.CharField(default='', help_text='客户名', max_length=100, verbose_name='客户名'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='recent_date',
            field=models.DateField(help_text='最近通讯时间', verbose_name='最近通讯时间'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='salesman',
            field=models.ForeignKey(help_text='所属业务员', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所属业务员'),
        ),
        migrations.AlterField(
            model_name='branchclient',
            name='tax_number',
            field=models.CharField(default='', help_text='税号', max_length=50, verbose_name='税号'),
        ),
    ]
