# Generated by Django 2.0.5 on 2019-01-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_client', '0002_auto_20190104_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchclient',
            options={'verbose_name': '海外客户', 'verbose_name_plural': '海外客户'},
        ),
    ]
