# Generated by Django 2.1.1 on 2019-01-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('branch_stock', '0001_initial'),
        ('branch_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overseas_invoice_num', models.CharField(help_text='出库单号', max_length=50, verbose_name='出库单号')),
                ('invoice_date', models.DateField(default='2000-01-01', help_text='出库日期', verbose_name='出库日期')),
                ('maker', models.CharField(help_text='经办人', max_length=30, verbose_name='经办人')),
                ('remark', models.CharField(help_text='备注', max_length=300, verbose_name='备注')),
                ('shipping_method', models.CharField(help_text='运输方式', max_length=300, verbose_name='运输方式')),
                ('branch_sales', models.ForeignKey(help_text='销售订单', on_delete=django.db.models.deletion.PROTECT, to='branch_sales.BranchSalesContract', verbose_name='销售订单')),
                ('branch_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_stock.BranchStock', verbose_name='仓库')),
            ],
        ),
        migrations.CreateModel(
            name='OverseasInvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='预计出库数量', verbose_name='预计出库数量')),
                ('real_count', models.IntegerField(default=0, help_text='实际出库数量', verbose_name='实际出库数量')),
                ('overseas_invoice', models.ForeignKey(help_text='出库单', on_delete=django.db.models.deletion.CASCADE, related_name='overseas_invoice_product', to='overseas_invoice.OverseasInvoice', verbose_name='出库单')),
                ('product', models.ForeignKey(help_text='出库产品', on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='出库产品')),
            ],
        ),
    ]
