# Generated by Django 2.1.1 on 2019-01-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domestic_invoice_num', models.CharField(default='', max_length=30, unique=True, verbose_name='国内发货单单号')),
                ('invoice_date', models.DateField(default='2000-01-01', verbose_name='发货时间')),
                ('estimated_date', models.DateField(default='2000-01-01', verbose_name='预计到达时间')),
                ('method', models.CharField(max_length=15)),
                ('freight', models.FloatField(default=0, verbose_name='运费')),
                ('address', models.CharField(max_length=30, null=True, verbose_name='地址')),
                ('bill', models.CharField(default='', max_length=30, verbose_name='提单号')),
                ('arrival_date', models.DateField(default='2000-01-01', null=True, verbose_name='到港日期')),
                ('clearance_date', models.DateField(default='2000-01-01', null=True, verbose_name='清关日期')),
                ('share_cost', models.FloatField(default=0, verbose_name='均摊总成本')),
                ('status', models.IntegerField(default=0)),
                ('remark', models.CharField(default='', max_length=30, verbose_name='其他信息')),
                ('total_amount', models.FloatField(default=0, verbose_name='总金额')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company', verbose_name='备货分公司')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticInvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='发货数量')),
                ('warehousing_count', models.IntegerField(default=0, verbose_name='入库数量')),
                ('unit_price', models.FloatField(default=0, verbose_name='海外成本(国内报价)')),
                ('unit_cost', models.FloatField(default=0, verbose_name='产品总价')),
                ('share_cost', models.FloatField(default=0, verbose_name='均摊成本')),
                ('add_cost', models.FloatField(default=0, verbose_name='额外成本')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='备注')),
                ('domestic_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_invoice_product', to='domestic_invoice.DomesticInvoice', verbose_name='国内发货单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.Product', verbose_name='发货产品')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=30, verbose_name='发送人')),
                ('info', models.CharField(default='', max_length=300, verbose_name='运输信息')),
                ('domestic_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_invoice.DomesticInvoice', verbose_name='发货单号')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
        ),
    ]
