# Generated by Django 2.1.1 on 2018-12-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_num', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('maker', models.CharField(default='', max_length=50, verbose_name='制单人')),
                ('storage_date', models.DateField(verbose_name='入库日期')),
                ('purchase_amount', models.FloatField(default=0, verbose_name='采购金额')),
                ('arrival_date', models.DateField(null=True, verbose_name='到港日期')),
                ('clearance_date', models.DateField(null=True, verbose_name='清关日期')),
                ('share_cost', models.FloatField(default=0, verbose_name='均摊总成本')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已入库'), (2, '审核未通过'), (3, '已退货(全部)')], default=0, verbose_name='入库状态')),
                ('remark', models.CharField(default='', max_length=500, verbose_name='备注')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseContract', verbose_name='采购单号')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
            },
        ),
        migrations.CreateModel(
            name='StorageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('share_cost', models.FloatField(default=0, verbose_name='均摊成本')),
                ('add_cost', models.FloatField(default=0, verbose_name='额外成本')),
                ('status', models.IntegerField(default=0, verbose_name='预留字段')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Storage', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '入库产品',
                'verbose_name_plural': '入库产品',
            },
        ),
    ]
