# Generated by Django 2.0.5 on 2018-12-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(default='', max_length=50, unique=True, verbose_name='出库单号')),
                ('maker', models.CharField(default='', max_length=50, verbose_name='经办人')),
                ('invoice_date', models.DateField(verbose_name='出库日期')),
                ('ship_method', models.CharField(choices=[('空运', '空运'), ('海运', '海运'), ('快递', '快递')], max_length=50, verbose_name='运输方式')),
                ('manifest_num', models.CharField(default='', max_length=50, verbose_name='发货单号')),
                ('contact', models.CharField(default='', max_length=100, verbose_name='联系方式')),
                ('address', models.CharField(default='', max_length=150, verbose_name='地址')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已出库'), (2, '审核未通过'), (3, '已退货(全部)')], default=0, verbose_name='出库状态')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
            },
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('count', models.IntegerField(verbose_name='出库数量')),
                ('plan_count', models.IntegerField(verbose_name='计划出库数量')),
                ('unit_price', models.FloatField(verbose_name='单价')),
                ('cost', models.FloatField(default=0, verbose_name='成本')),
                ('status', models.IntegerField(default=0, verbose_name='预留字段')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='出库单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '出库单产品',
                'verbose_name_plural': '出库单产品',
            },
        ),
    ]
