# Generated by Django 2.0.5 on 2018-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinquiryproduct',
            name='kk',
            field=models.IntegerField(default=0),
        ),
    ]
