# Generated by Django 2.0.5 on 2018-12-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_inquiry', '0002_branchinquiryproduct_kk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchinquiryproduct',
            name='kk',
        ),
    ]
