# Generated by Django 2.1.1 on 2018-09-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='仓库名')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='总数量')),
                ('unit_cost', models.FloatField(default=0, verbose_name='平均成本')),
                ('bad_count', models.IntegerField(default=0, verbose_name='不良品数量')),
                ('recent_date', models.DateField(verbose_name='最近入库时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库产品',
                'verbose_name_plural': '仓库产品',
            },
        ),
    ]
