# Generated by Django 2.1.1 on 2018-09-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180926_1607'),
        ('stock', '0002_stock_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=20, verbose_name='申请人')),
                ('reviewer', models.CharField(max_length=20, verbose_name='审核人')),
                ('order_num', models.CharField(max_length=20, verbose_name='单号')),
                ('unit_price', models.FloatField(default=0, verbose_name='售价')),
                ('cost_unit_price', models.FloatField(default=0, verbose_name='成本')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('in_or_out', models.IntegerField(choices=[(0, '出库'), (1, '入库')], default=0, verbose_name='出/入库')),
                ('reason', models.CharField(default='normal', max_length=300, verbose_name='原因')),
                ('date', models.DateField(verbose_name='日期')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock', verbose_name='仓库')),
            ],
        ),
    ]
