# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='por_count',
            field=models.IntegerField(default=0, verbose_name='需求数量'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='sr_count',
            field=models.IntegerField(default=0, verbose_name='在途数量'),
        ),
    ]
