# Generated by Django 2.0.5 on 2018-12-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20181225_0920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domestic_invoice_num', models.CharField(default='', max_length=30, unique=True, verbose_name='国内发货单单号')),
                ('method', models.CharField(max_length=15)),
                ('address', models.CharField(default='', max_length=30, unique=True, verbose_name='地址')),
                ('bill', models.CharField(default='', max_length=30, verbose_name='提单号')),
                ('remark', models.CharField(default='', max_length=30, verbose_name='其他信息')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company', verbose_name='备货分公司')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=30, verbose_name='发送人')),
                ('info', models.CharField(default='', max_length=300, verbose_name='运输信息')),
                ('domestic_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_invoice.DomesticInvoice', verbose_name='发货单号')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
        ),
    ]
