# Generated by Django 2.0.5 on 2018-12-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('domestic_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticInvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='发货数量')),
                ('unit_price', models.FloatField(default=0, verbose_name='海外成本(国内报价)')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='domesticinvoice',
            name='freight',
            field=models.FloatField(default=0, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='domesticinvoiceproduct',
            name='domestic_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_invoice.DomesticInvoice', verbose_name='国内发货单'),
        ),
        migrations.AddField(
            model_name='domesticinvoiceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='发货产品'),
        ),
    ]
