# Generated by Django 2.0.5 on 2018-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_invoice', '0002_auto_20181225_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticinvoice',
            name='estimated_date',
            field=models.DateField(default='2000-01-01', verbose_name='预计到达时间'),
        ),
        migrations.AddField(
            model_name='domesticinvoice',
            name='invoice_date',
            field=models.DateField(default='2000-01-01', verbose_name='发货时间'),
        ),
    ]
