# Generated by Django 2.0.5 on 2018-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_invoice', '0003_auto_20181225_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticinvoice',
            name='arrival_date',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='到港日期'),
        ),
        migrations.AddField(
            model_name='domesticinvoice',
            name='clearance_date',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='清关日期'),
        ),
        migrations.AddField(
            model_name='domesticinvoice',
            name='share_cost',
            field=models.FloatField(default=0, verbose_name='均摊总成本'),
        ),
        migrations.AddField(
            model_name='domesticinvoiceproduct',
            name='add_cost',
            field=models.FloatField(default=0, verbose_name='额外成本'),
        ),
        migrations.AddField(
            model_name='domesticinvoiceproduct',
            name='share_cost',
            field=models.FloatField(default=0, verbose_name='均摊成本'),
        ),
        migrations.AddField(
            model_name='domesticinvoiceproduct',
            name='warehousing_count',
            field=models.IntegerField(default=0, verbose_name='入库数量'),
        ),
    ]
