# Generated by Django 2.0.5 on 2019-01-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_invoice', '0004_auto_20181226_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticinvoice',
            name='address',
            field=models.CharField(max_length=30, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='domesticinvoiceproduct',
            name='domestic_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_invoice_product', to='domestic_invoice.DomesticInvoice', verbose_name='国内发货单'),
        ),
        migrations.AlterField(
            model_name='domesticinvoiceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.Product', verbose_name='发货产品'),
        ),
    ]
