# Generated by Django 2.1.1 on 2018-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180921_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='amount',
            field=models.FloatField(default=0, verbose_name='金额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='discount',
            field=models.FloatField(default=0, verbose_name='折扣'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='receivable_amount',
            field=models.FloatField(default=0, verbose_name='应收金额'),
            preserve_default=False,
        ),
    ]
