# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('product', '0005_auto_20181030_2128'),
        ('client', '0006_client_is_branch'),
        ('sales', '0003_auto_20180928_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('year', models.IntegerField(default=2018, verbose_name='年')),
                ('month', models.IntegerField(default=1, verbose_name='月')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Client', verbose_name='客户')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company', verbose_name='公司')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
            ],
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='discount',
            field=models.FloatField(default=0, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='receivable_amount',
            field=models.FloatField(default=0, verbose_name='应收金额'),
        ),
    ]
