# Generated by Django 2.1.1 on 2018-11-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20181030_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescontract',
            old_name='exchange_rate',
            new_name='exrate',
        ),
    ]
