# Generated by Django 2.1.1 on 2018-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='permission_level',
            field=models.IntegerField(default=1, verbose_name='权限等级'),
        ),
    ]
