# Generated by Django 2.1.1 on 2019-01-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20181210_1543'),
        ('sales', '0002_auto_20181210_1543'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualpayment',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseContract', verbose_name='采购合同'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualreceipts',
            name='sales',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesContract', verbose_name='销售合同'),
            preserve_default=False,
        ),
    ]
