# Generated by Django 2.0.5 on 2018-12-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWarehousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_num', models.CharField(default='', max_length=20, unique=True, verbose_name='入库单号')),
            ],
        ),
    ]
