# Generated by Django 2.0.5 on 2018-12-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_stock', '0002_branchstockrecord'),
        ('product', '0001_initial'),
        ('domestic_invoice', '0004_auto_20181226_0949'),
        ('branch_warehousing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWarehousingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='入库数量')),
                ('remark', models.CharField(default='', max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='入库产品')),
            ],
        ),
        migrations.RenameField(
            model_name='branchwarehousing',
            old_name='odd_num',
            new_name='warehousing_num',
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='branch_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch_stock.BranchStock', verbose_name='仓库'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='domestic_invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domestic_invoice.DomesticInvoice', verbose_name='国内发货单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='remark',
            field=models.CharField(default='', max_length=500, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='share_cost',
            field=models.FloatField(default=0, verbose_name='均摊总成本'),
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='status',
            field=models.IntegerField(default=0, verbose_name='入库状态'),
        ),
        migrations.AddField(
            model_name='branchwarehousing',
            name='warehousing_date',
            field=models.DateField(default='2000-01-01', verbose_name='入库时间'),
        ),
        migrations.AddField(
            model_name='branchwarehousingproduct',
            name='warehousing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_warehousing.BranchWarehousing', verbose_name='海外入库单'),
        ),
    ]
