# Generated by Django 2.1.1 on 2018-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='', max_length=100, verbose_name='客户公司名'),
        ),
    ]
