# Generated by Django 2.1.1 on 2018-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='邮箱'),
        ),
    ]
