# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180926_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_branch',
            field=models.BooleanField(default=False, verbose_name='是否分公司'),
        ),
    ]
