# Generated by Django 2.1.1 on 2019-01-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_inquiry_num', models.CharField(default='', max_length=20, unique=True, verbose_name='询价单号')),
                ('inquiry_date', models.DateField(verbose_name='询价日期')),
                ('branch_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branch_client.BranchClient', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='BranchInquiryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=20, verbose_name='型号')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('spec', models.CharField(default='', max_length=100, verbose_name='规格要求')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('mesu_unit', models.CharField(max_length=10, verbose_name='单位')),
                ('package', models.CharField(max_length=60, verbose_name='包装要求')),
                ('unit_price', models.FloatField(default=0, verbose_name='单价')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('branch_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_inquiry.BranchInquiry', verbose_name='询价单')),
            ],
        ),
    ]
