# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageproduct',
            old_name='purchase',
            new_name='storage',
        ),
    ]
