# Generated by Django 2.1.1 on 2018-09-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, verbose_name='流水号')),
                ('product_id', models.CharField(max_length=20, unique=True, verbose_name='产品ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='产品图片')),
                ('name', models.CharField(max_length=50, verbose_name='产品型号')),
                ('spec', models.CharField(max_length=100, verbose_name='产品规格')),
                ('eng_name', models.CharField(default='', max_length=50, verbose_name='产品型号(英语)')),
                ('eng_spec', models.CharField(default='', max_length=100, verbose_name='产品规格(英语)')),
                ('spanish_name', models.CharField(default='', max_length=100, verbose_name='产品型号(西班牙语)')),
                ('spanish_spec', models.CharField(default='', max_length=100, verbose_name='产品规格(西班牙语)')),
                ('mexico_name', models.CharField(default='', max_length=100, verbose_name='产品型号(墨西哥)')),
                ('mexico_spec', models.CharField(default='', max_length=100, verbose_name='产品规格(墨西哥)')),
                ('peru_name', models.CharField(default='', max_length=100, verbose_name='产品型号(秘鲁)')),
                ('peru_spec', models.CharField(default='', max_length=100, verbose_name='产品规格(秘鲁)')),
                ('mesu_unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('volume', models.FloatField(default=0, verbose_name='单位体积')),
                ('barcode', models.CharField(default='', max_length=20, verbose_name='条形码')),
                ('customs_code', models.CharField(default='', max_length=20, verbose_name='海关代码')),
                ('carton_size', models.FloatField(default=0, verbose_name='外箱体积')),
                ('carton_weight', models.FloatField(default=0, verbose_name='外箱毛重')),
                ('main_supplier', models.CharField(default='', max_length=50, verbose_name='主供应商')),
                ('cost', models.FloatField(default=0.0, verbose_name='成本(RMB)')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='产品类名')),
                ('type_id', models.CharField(max_length=20, unique=True, verbose_name='类ID')),
                ('type_pid', models.CharField(default='0', max_length=20, verbose_name='父类ID')),
                ('is_parent', models.BooleanField(verbose_name='是否还有子类')),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductType', verbose_name='产品类别'),
        ),
    ]
