# Generated by Django 2.1.1 on 2018-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180926_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=200, unique=True, verbose_name='产品型号'),
        ),
    ]
