# Generated by Django 2.1.1 on 2018-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181015_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_type',
            field=models.CharField(default='', max_length=50, verbose_name='产品大类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=20, unique=True, verbose_name='产品型号'),
        ),
    ]
