# Generated by Django 2.1.1 on 2018-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181015_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=15, verbose_name='产品型号'),
        ),
    ]
