# Generated by Django 2.0.5 on 2019-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overseasinvoice',
            name='shipping_method',
            field=models.CharField(help_text='运输方式', max_length=300, verbose_name='运输方式'),
        ),
    ]
