# Generated by Django 2.0.5 on 2019-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_invoice', '0002_auto_20190109_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseasinvoiceproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='OverseasInvoiceProduct',
        ),
    ]
